remove external css and aplly tailwind css
Pks20/user-posts pull request #1
Opened 2024-12-12 10:41 UTC by Pks20

2024-12-13 11:26 UTC, 10shubham01 commented on user-posts/components/FooterComponent.vue
> +  goToPage: (page: number) => void;
check this out 
https://vuejs.org/guide/components/events

2024-12-13 11:29 UTC, 10shubham01 commented on user-posts/components/FormModal.vue
> +      <form @submit.prevent="handleSubmit">
use https://ui.nuxt.com/components/form

2024-12-13 11:33 UTC, 10shubham01 requested changes

2024-12-13 11:33 UTC, 10shubham01 commented on user-posts/components/FormModal.vue
> +<script setup lang="ts">
https://ui.nuxt.com/components/modal

2024-12-13 11:33 UTC, 10shubham01 commented on user-posts/pages/index.vue
> +
Refactor this ... use https://ui.nuxt.com/components/notification to show toast for error or successful CRUD

2024-12-16 05:13 UTC, 10shubham01 approved these changes

2024-12-16 05:14 UTC, archit-credilio approved these changes

2024-12-16 05:20 UTC, merged